from ad_data import AdData
from recommender import Recommender
from ads_database import AdsDatabase
from recommender_engine import RecommenderEngine


db = AdsDatabase()
engine = RecommenderEngine(db)
recommender = Recommender(db, engine)

dzb = AdData(hyperlink='dzb', description='Ostatnia część "dolarowej trylogii" Sergia Leone. Trzej mężczyźni, Zły - bezwzględny łowca nagród, Brzydki - wielokrotny przestępca, Dobry - łowca głów z zasadami, usiłują dotrzeć do skarbu ukrytego przez wojsko. Brzydki jest w posiadaniu informacji o nazwie cmentarza, na którym został on zakopany, Dobry zna nazwisko na poszukiwanym grobie. Czyni to z nich mimowolny zespół. Po piętach depcze im Zły.',tags=[])
kdw = AdData(hyperlink='kdw', description='Kiedy dwaj rywalizujący ze sobą łowcy nagród (nagrodzony Oscarem Clint Eastwood oraz Lee Van Cleef) orientują się, że ścigają tego samego bandytę, łączą siły w nadziei doprowadzenia go przed oblicze sprawiedliwości. Jednak wraz z rozwojem akcji, sprawy coraz bardziej się komplikują. Zobacz mocną, drugą część sagi Sergia Leone, w której Eastwood wciela się w osławionego „Człowieka bez imienia”.', tags=[])
zkd = AdData(hyperlink='zkd', description='Samotny wędrowiec Joe (Clint Eastwood) przybywa do miasteczka leżącego przy granicy meksykańsko-amerykańskiej. Wpływy dzielą tu między siebie dwie rywalizujące bandy przemytników. Przebiegły Joe dostrzega szansę na zarobek, lokując się pomiędzy skonfliktowanymi stronami, co realizuje zatrudniając się raz w jednej, raz w drugiej grupie. Wkrótce wtrąca się również w losy lokalnej rodziny, rozdzielonej przez bandytów. W rezultacie ściąga na siebie wrogość jednego z rodów, doprowadzając do eskalacji trwającego konfliktu', tags=[])
dpl = AdData(hyperlink='dpl', description='Deadpool powrócił i znów dokazuje na całego: przerabia wrogów na kotlety siekane, pokazuje język współczesnej popkulturze, spędza sen z powiek strażnikom dobrego smaku oraz poprawności politycznej. Trudno jednak oprzeć się wrażeniu, że artystyczna strategia, która w pierwszym filmie działała bez większych zarzutów, tym razem zaczęła szwankować. Zamiast rebelianckiego ducha z sequela bije bowiem głównie rutyna pomieszana z nieznośnym samozachwytem.', tags=[])
zkb = AdData(hyperlink='zkb', description='Maturzysta dostojnej szkoły (Chris O Donnell) zostaje zamieszany w uczniowską aferę, która stawia go wobec dylematu: donieść na kolegów i ocalić własną skórę, czy też odmówić współpracy i ocalić honor. Podczas długiego weekendu podejmuje się opieki nad niewidomym, emerytowanym oficerem (Al Pacino). Niełatwy podopieczny zarządza wspólną wyprawę do Nowego Jorku, której program obejmuje pobyt w hotelu Astoria, wizyty w drogich restauracjach, łóżkowe spotkania z piękną kobietą', tags=[])
hso = AdData(hyperlink='hso', description='Możecie odetchnąć z ulgą. Młodość kosmicznego awanturnika wygląda dokładnie tak, jak to sobie wyobrażaliście. Pełna jest buńczucznych okrzyków, podwójnych blefów i nadrabiania miną. Zaś film o przygodach nieopierzonego Hana Solo to rozrywka sfastrygowana pod gust wieloletnich fanów gwiezdnowojennej sagi. Zaskakująco dojrzała i niewystarczająco szalona. Nakręcona po bożemu, lecz bez bożej iskry', tags=[])
lsc = AdData(hyperlink='lsc', description='Historia tytułowego Schindlera jest bowiem historią niezwykłą. To opowieść o tym jak jeden człowiek zdołał uratować ponad tysiąc istnień ludzkich bez użycia broni, a wykorzystując tylko swój osobisty wdzięk. To dowód na to, że decyzje podejmowane przez jednostkę mogą zmienić losy tysięcy innych. To opowieść wzruszająca, pozbawiona jednak nadmiernej ckliwości - jeśli po policzkach spływają nam łzy, to przyczyną tego jest sama realność pozbawionej reżyserskich i operatorskich tricków fabuły, oraz naturalne przerażenie wywołane horrorem oglądanej wojny i współczucie dla jej ofiar. ', tags=[])
plf = AdData(hyperlink='plf', description='Płatni mordercy, Jules (Samuel L. Jackson) i Vincent (John Travolta), dostają zlecenie, by odzyskać z rąk przypadkowych rabusiów tajemniczą walizkę bossa mafii. Nie dość tego, Vincent dostaje kolejną robotę - na czas nieobecności gangstera w mieście ma zaopiekować się jego poszukującą wrażeń żoną Mią (Uma Thurman). Vincent i Jules niespodziewanie wpadają po uszy, gdy przypadkowo zabijają zakładnika. Kłopoty ma też podupadły bokser (Bruce Willis), który otrzymał dużą sumę za', tags=[])
zjp = AdData(hyperlink='zjp', description='Komedia, której głównym tematem jest... holocaust. Błaznowaty wieśniak przybywa do dużego miasta w Toskanii, zakłada rodzinę. Wybucha wojna, wkraczają Niemcy, wieśniak, jako pół-Żyd trafia do obozu koncentracyjnego wraz z najbliższą rodziną. Próbuje jednak przekonać syna, że pobyt w obozie jest jedynie pewną formą zabawy dla dorosłych.', tags=[])
djg = AdData(hyperlink='djg', description='Z jednej strony pastisz, z drugiej – hołd dla gatunku. Obydwa światy spotykają się w "Django" na  podobnych zasadach co w poprzednich filmach Tarantino. Ich zderzenie widać w niepodrabialnej inscenizacji, słychać w ostrych jak brzytwa dialogach, czuć w rytmie poszczególnych ujęć i scen. "Django" udowadnia jednak, że konwencja westernu nie jest tak elastyczna jak gatunek kina wojennego, samurajskiego czy blaxploitation i że o wiele trudniej uwolnić ją od balastu nostalgii.', tags=[])
mow = AdData(hyperlink='mow', description='Agentce FBI, Clarise Starling, zostaje powierzona sprawa "Buffalo Billa", seryjnego mordercy wyróżniającego się szczególnym okrucieństwem wobec swych ofiar, które odziera ze skóry. Sprawę pomaga jej rozwikłać inny, niezwykle inteligentny i niebezpieczny morderca - Hannibal Lecter - pacjent więziennego centrum psychiatrycznego. Hannibal jest zauroczony Clarice, a w zamian za odkrywanie przez nią części swej przeszłości, kawałek po kawałku odkrywa dla niej tajemnicę morderstw.', tags=[])
krl = AdData(hyperlink='krl', description='Legenda powraca. By zarobić jeszcze więcej. Na szczęście nie w jednym ze słabych sequeli, z którymi studio Disneya niszczy od lat dziecięce gusta. "Król Lew" doczekał się dwóch takich kontynuacji, ale  teraz, po 17 latach swoją drugą szansę w kinach dostaje oryginalny film z 1994 roku – tyle że przetransferowany do formatu 3D. Inaczej niż w przypadku odświeżonego "Toy Story", na warsztat poszła animacja rysowana, ale jednak nie całkiem klasyczna.', tags=[])

db.add_ads([dzb, kdw, zkd, dpl, zkb, hso, lsc, plf, zjp, djg, mow, krl])

print(recommender.find_similar(['dzb', 'kdw'], 4))